name: walletika_api
description: Walletika API cloud services.
version: 1.0.0
homepage: https://github.com/walletika
repository: https://github.com/walletika/walletika-api
issue_tracker: https://github.com/walletika/walletika-api/issues
platforms:
  android:
  ios:
  linux:
  macos:
  windows:
publish_to: none

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  path: ^1.8.2
  coingecko_api: ^1.1.0
  aescrypto:
    git:
      url: https://github.com/MahmoudKhalid/aescrypto-dart.git
      ref: main

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
